### ISSUE TITLE
How do you use these commands?

### ISSUE THREAD

**Issue by ghost** [LA3QMA/TH-D74-Kenwood#11]
I'm testing the 'BL' command using python. I tried this, but get no response. I've tried adding a '\n' to the command, but still see nothing.
thanks,
Bob

		ser = serial.Serial(
					port='/dev/ttyACM0',
					baudrate = 9600,
					parity = serial.PARITY_NONE,
					stopbits = serial.STOPBITS_ONE,
					bytesize = 8,
					timeout = 1
				)

		b = bytes('BL', 'utf-8')
		ser.write(b)
		b = ser.read(100)						# Adjust size according to expected response
		resp = b.decode()
		if resp != '':
			print(resp)

**Comment by emrecio** [comment]
Unknown, have you tried the terminal application on your machine first to make sure comms working and set up correctly (minitel or the like?)

**Comment by ghost** [comment]
I think that serial comms works. If I manually set the radio to kiss mode I can send kiss commands and they work.

**Comment by LA3QMA** [comment]
The BL command doesnt need any parameter so it should just work. I have not tried your python code but it seems correct. But keep in mind that the radio is not happy if you read/write to fast. I usually have a 150ms delay between each commands.

You also have to read until the end. ie. if you are waiting for 100bytes your code is not going to display anything.

BL is returning 1byte.

ser.readline() could work but the radio usually doesnt respond with a CR/LF or other 

So i would suggest to read a loop and append each received character.

**Comment by ghost** [comment]
This code actually worked once, but failed to get a response several other times.
```
ser = serial.Serial('/dev/ttyACM0', timeout=1.0)
time.sleep(1)
b = bytes('BL', 'utf-8')
ser.write(b)
b = ser.read(ser.in_waiting)
resp = b.decode()
if resp != '':
	print(resp)
ser.close()
ser = None
```

I was trying appending \n or \r to the command. I'm not sure if I had appended anything to the command when it worked. But I've tried it since then in all combinations and can't get it to work a second time. When it did work it returned:
BL 3

**Comment by LA3QMA** [comment]
This should work:

```
import serial
import time


def main():
    try:
        # Open serial port with read and write timeouts set to 150ms
        ser = serial.Serial('COM4', 9600, timeout=0.15, write_timeout=0.15)
        time.sleep(2)  # Wait for the serial connection to initialize

        # Send the command "BL" followed by CRLF (carriage return and line feed)
        command = "ID\r"
        ser.write(command.encode())

        # Read the response from the serial device until no data is received
        response = ""
        while True:
            line = ser.readline().decode('utf-8').strip()
            if not line:
                break
            response += line + "\n"

        print(f"Response:\n{response}")

    except serial.SerialException as e:
        print(f"Error: {e}")
    finally:
        # Close the serial port
        if ser.is_open:
            ser.close()


if __name__ == "__main__":
    main()

```


Tested on windows as my linux was occupied.

**Comment by ghost** [comment]
It still prints nothing. I only changed 'COM4' to '/dev/ttyACM0'.
I tried more variations and got it to work a second time. the command was 'BL\n', but the same command (with slow human delay) did not work after that. I tried it a few times.

**Comment by LA3QMA** [comment]
Then i tried from my linux:

(venv) kgb@kgb:~/PycharmProjects/thd74$ python main.py 
Response:
ID TH-D74

Response:
BL 2

(venv) kgb@kgb:~/PycharmProjects/thd74$ ls -alh /dev/ttyACM0 
crw-rw---- 1 root dialout 166, 0 juli  17 21:37 /dev/ttyACM0
(venv) kgb@kgb:~/PycharmProjects/thd74$

**Comment by LA3QMA** [comment]
If the TNC is enabled you cannot control the radio as in "CAT". But you can send/receive data.
I have not tried sending C0 FF C0 to exit KISS MODE. So if you are in kiss mode and/or have been using TC 0 or TC 1 command you should power off the radio.

In APRS mode you can control the radio.

**Comment by ghost** [comment]
I got it working. The python code works. The problem was that 'CTCSS' was displayed on the screen (I think). I pressed '5' / 'tone' until no icon was showing. I *think* that's the only change I made. It works every time now with either 'APRS 12' or 'none' being displayed. I just got the radio and don't know about a lot of these things. It will be good to be able to control it with the listed commands.

```
b = bytes('BL\r', 'utf-8')

try:
    ser = serial.Serial('/dev/ttyACM0', 9600, timeout=0.15, write_timeout=0.15)
    time.sleep(2)  # Wait for the serial connection to initialize

    if not ser.is_open:
        raise Exception('serial port not open')
    settings = ser.get_settings()

    ser.write(b)
    time.sleep(0.15)
    b = ser.read(ser.in_waiting)
    resp = b.decode()
    if resp != '':
        resp = resp.strip()
        print('\n%s' % (resp))
    else:
        print('\nNO RESPONSE')
except serial.SerialException as e:
    raise
finally:
    if ser.is_open:
        ser.close()
        ser = None

```

**Comment by LA3QMA** [comment]
It should work regardless if the subtone is active or not. It should also work in aprs mode.
For the TH-D75 the manual informs how to exit if in KISS MODE and maybe this works for the TH-D72/74/7x0.
Anyhow good that you got things to work. :-)

**Comment by ghost** [comment]
I iterated through the commands (mostly just reads). All worked. Some needed a  parameter so the radio returned '?'. I did add a parameter for the 'MD' command. Some of the commands actually controlled the radio, like TX, RX, DW, UP. It will take more time to test all of the setters.

 1  AE      C4310594,K01    Radio serial number and model
 2  AG               021    AF Gain
 3  AI                 0    Realtime feedback on frequency change etc
 4  AS                 0    TNC baudrate
 5  BC                 0    PTT and CTRL Band
 6  BE                 N    APRS Beacon
 7  BL                 4    Battery level
 8  BS                 1    Bar antenna
 9  BT                 1    Bluetooth
10  BY                 ?    Squelch open/closed
11  CS             xxxxx    Callsign
12  DC                 ?    D-Star slot,callsign,msg
13  DL                 1    Dual Band Mode/Single Band Mode
14  DS                 1    D-Star callsign slot
15  DW                DW    Emulates the Microphone Down Key
16  FO      0088700000,0000000000,B,B,8,0,1,0,0,0,0,0,0,08,08,000,0,CQCQCQ,0,00    VFO channel
17  FQ        0144355000    Frequency
18  FR                 0    FM radio
19  FS                 1    Fine step
20  FT                 0    Fine tuning status
21  FV              1.02    Firmware version
22  GM                 0    Radio/GPS
23  GP               1,0    Internal GPS
24  GS       1,0,0,0,1,0    GPS sentence
25  ID            TH-D75    Radio Model
26  IO                 0    Get/set IF outputmode
27  LC                 1    Display light
28  MD 0               0    Band A mode
29  MD 1               8    Band B mode
30  ME                 ?    Memory channel, frequency, offset etc
31  MR                 ?    Memory channel
32  MS                 0    My position
33  PC                 ?    Output power
34  PS                 1    Master power??
35  PT                 2    Beacon control
36  RA                 ?    Attenuator
37  RT      240718073928    Time
38  SF                 ?    Receive step size
39  SH                 ?    Filter cutoff
40  SM                 ?    S-meter
41  SQ                 ?    Squelch status
42  SR                 ?    Reset
43  TN               0,0    KISS TNC
44  TX                 0    Transmit
45  RX                RX    Receive
46  TY               K,2    Radio Type
47  UP                UP    Emulates the Microphone Up Key
48  VD                 0    VOX delay
49  VG                 4    VOX Gain
50  VM                 ?    Memory/VFO
51  VX                 0    VOX on/off

**Comment by emrecio** [comment]
@BobSelf let's talk. I am looking to not duplicate efforts.

**Comment by ghost** [comment]
@emrecio I don't know how to contact you.
