### ISSUE TITLE
Documentation missing?

### ISSUE THREAD

**Issue by spikebike** [LA3QMA/TH-D74-Kenwood#6]
I was hoping to program the D74 memories for my local repeaters.  Did I miss them?  Do you know of any similar resources?  I'm running linux so the Kenwood provided software is not an option.

**Comment by LA3QMA** [comment]
You could eiter make a script programming your radio using the commands or i.e CHIRP.
https://chirp.danplanet.com/projects/chirp/wiki/Home not sure if it supports the TH-D74.

I'm only documenting the commands so that other people can implement this in i.e CHIRP or make their own software.
