### ISSUE TITLE
Exit KISS mode

### ISSUE THREAD

**Issue by georges** [LA3QMA/TH-D74-Kenwood#9]
I can confirm that the 0xC0, 0xFF, 0xC0 sequence exit KISS mode when issued via USB.

However, I was not able to get it to work via Bluetooth, it never exited for me.

I also found this in the THD-74 user manual:

After exiting KISS mode with the KISS command “C0,FF,C0” (192,255,192) and when KISS mode is set to ON with a command from the PC, use the PC command "TN 2,0"(Data Band:A Band) or "TN 2,1"(Data Band:B Band) in TH-D74.

Which seems weird because the TN 2,x command would put it *in* KISS mode again.

**Comment by LA3QMA** [comment]
Tnx. Could it be that when issuing the TN2,x command after KISS is enabled its been reset to be in regular TNC mode?
You can check this by connecting a terminal software to the radio and press enter. You can then i.e issue a command like DISP to show all available values.

**Comment by georges** [comment]
Actually I had a bug in my experimentation. I can now confirm that `0xC0,0xFF,0xC0` will exit KISS mode in both bluetooth and USB mode.
